"""+ SyncState model

Revision ID: 091651f7dd21
Revises: 
Create Date: 2026-05-27 01:30:07.619005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091651f7dd21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_meta')
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=True))

    op.create_table('contract_meta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('books_sales_order_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('in_network', sa.BOOLEAN(), nullable=True),
    sa.Column('buyer_reference', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('books_sales_order_id')
    )
    # ### end Alembic commands ###
