"""- in_network column from contracts

Revision ID: 2211e62d7be7
Revises: c1a2905e04f3
Create Date: 2026-06-09 15:25:20.965283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2211e62d7be7'
down_revision = 'c1a2905e04f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('in_network')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_network', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
