"""+ is_declined to Contract

Revision ID: 2b0e0cf9d45b
Revises: 091651f7dd21
Create Date: 2026-05-27 17:53:28.756510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0e0cf9d45b'
down_revision = '091651f7dd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_declined', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('is_declined')

    # ### end Alembic commands ###
