"""add paid_status to contracts

Revision ID: 3452258f3fbf
Revises: 39ee66621a8a
Create Date: 2026-07-09 03:49:10.377652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3452258f3fbf'
down_revision = '39ee66621a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('paid_status')

    # ### end Alembic commands ###
