"""Add task scheduling fields: scheduled_date, delay_minutes, is_visible

Revision ID: 39ee66621a8a
Revises: 2211e62d7be7
Create Date: 2026-06-24 22:31:48.352230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ee66621a8a'
down_revision = '2211e62d7be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('cf_item_contract_price',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delay_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_visible')
        batch_op.drop_column('delay_minutes')
        batch_op.drop_column('scheduled_date')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('cf_item_contract_price',
               existing_type=sa.String(length=100),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
