"""add nationality to users

Revision ID: 8c8b91c5d34b
Revises: 2b0e0cf9d45b
Create Date: 2026-06-02 15:32:19.745409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b91c5d34b'
down_revision = '2b0e0cf9d45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
