"""+ pic_employee_id on contracts

Revision ID: c1a2905e04f3
Revises: 8c8b91c5d34b
Create Date: 2026-06-09 15:07:42.547756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a2905e04f3'
down_revision = '8c8b91c5d34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_employee_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('pic_employee_id')

    # ### end Alembic commands ###
